server:
    port: 8081

spring:
    application:
        name: user-service
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8083/realms/task-manager

            client:
                registration:
                    keycloak:
                        client-id: my-client
                        client-secret: WpkY4je69RGG9Jbirnwli1MdBiYBrGXF
                        scope: openid, profile, email
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8083/realms/task-manager

#    datasource:
#        url: jdbc:postgresql://postgres-user:5433/task-manager-user_db
#        username: admin
#        password: pass
#        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
    swagger-ui:
        oauth2-redirect-url: http://localhost:8081/swagger-ui/oauth2-redirect.html
        oauth:
            client-id: my-client
            client-secret: WpkY4je69RGG9Jbirnwli1MdBiYBrGXF
            use-pkce-with-authorization-code-grant: true
    api-docs:
        enabled: true
        default-consumes-media-type: application/json
        default-produces-media-type: application/json
