server:
    port: 8081

spring:
    application:
        name: user-service
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8083/realms/task-manager

            client:
                registration:
                    keycloak:
                        client-id: my-client
                        client-secret: wNI52dSWvnTvxTpZGXmcOHeaCQfOGPU5
                        scope: openid, profile, email
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8083/realms/task-manager


springdoc:
    swagger-ui:
        oauth2-redirect-url: http://localhost:8081/swagger-ui/oauth2-redirect.html
        oauth:
            client-id: my-client
            client-secret: wNI52dSWvnTvxTpZGXmcOHeaCQfOGPU5
            use-pkce-with-authorization-code-grant: true
    api-docs:
        enabled: true
        default-consumes-media-type: application/json
        default-produces-media-type: application/json
